Repository Guavus/incubator-superset, pull requests merged in 2020-04, with the labels that each got.

#288 fix(CI):removed MarkupSafe as deps from pipfile and updated lock file
  Pipfile
  Pipfile.lock
  setup.py
Labels: #bug

#284 fix(pr_template) : updated pr_template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: #bug, #inner-source, .vzw-iot

#282 fix(log-level) : Change log level info to debug
  superset/connectors/sqla/models.py
  superset/hive_query.py
  superset/models/core.py
  superset/viz.py
Labels: #bug, #inner-source, .vzw-iot

#281 feat(dash-navigation): Configuration to enable/disable passing filter, when navigating to Dashboard B from Dashboard A .
  superset/assets/spec/javascripts/dashboard/components/SliceHeaderControls_spec.jsx
  superset/assets/src/chart/chartAction.js
  superset/assets/src/dashboard/components/SliceHeaderControls.jsx
  superset/assets/src/explore/controlPanels/sections.jsx
  superset/assets/src/explore/controls.jsx
Labels: #enhancement, #inner-source

#285 fix(cursor-style): Show cursor pointer/not-allowed on table and leaflet map
  superset/assets/src/visualizations/LeafletMap/LeafletMap.css
  superset/assets/src/visualizations/LeafletMap/LeafletMap.js
  superset/assets/src/visualizations/Table/Table.js
Labels: #bug, #inner-source, .vzw-iot

#286 fix(geojson-validator): added geojson validator and logger
  superset/assets/package-lock.json
  superset/assets/package.json
  superset/assets/src/visualizations/LeafletMap/LeafletMap.js
Labels: #bug, #inner-source, .vzw-iot
